filemap:
  markers:
    groups:
    - name: IFS # interfaces
      ru-desc: Настройка имен интерфейсов
      en-desc: Interfaces names setup
      members:
      - name: ISP-IF
        ru-desc: Интерфейс для соединения c ISP
        en-desc: Interface for ISP connection
        value: enp0s3
      - name: BR-SRV-IF
        ru-desc: Интерфейс для соединения c HQ-SRV
        en-desc: Interface for HQ-SRV connection
        value: enp0s8
      - name: TUN-IF
        ru-desc: Интерфейс для gre соединения c BR-R
        en-desc: Interface for gre BR-R connection
        value: tun1

    - name: IPS # addresses and masks
      ru-desc: Настройка адресов интерфейсов
      en-desc: Interfaces addresses setup
      generic:
        src-group: IFS
        iterate:
        - append: -IP4
          ru-desc: Ipv4 адрес для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv4 address for $GENERIC-MEMBER$value interface
          values: [33.33.33.2, 192.168.2.1, 10.0.5.2]
        - append: -MASK4
          ru-desc: Ipv4 маска для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv4 mask for $GENERIC-MEMBER$value interface
          values: [24, 24, 30]
        - append: -IP6
          ru-desc: Ipv6 адрес для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv6 address for $GENERIC-MEMBER$value interface
          values: [2000:2::2, 2000:2::1:1, 2001::2]
        - append: -MASK6
          ru-desc: Ipv6 маска для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv6 mask for $GENERIC-MEMBER$value interface
          values: [112, 112, 124]

    - name: TUNOPT
      ru-desc: Настройка некоторых параметров GRE
      en-desc: Several GRE options
      members:
      - name: HQ-R-IP4
        ru-desc: Ipv4 адрес BR-R внешний
        en-desc: Ipv4 address of BR-R external
        value: 22.22.22.2

    - name: RTR # router
      ru-desc: Адреса роутера
      en-desc: Router addresses
      members:
      - name: ISP-IP4
        ru-desc: Ipv4 адрес ISP
        en-desc: Ipv4 address of ISP
        value: $ISP-IF-IP4$value|get_first_addr
      - name: ISP-IP6
        ru-desc: Ipv6 адрес ISP
        en-desc: Ipv6 address of ISP
        value: $ISP-IF-IP6$value|get_first_addr

    - name: DNS # dns
      ru-desc: Настройка имен интерфейсов
      en-desc: Interfaces names setup
      members:
      - name: DNSSRV1
        ru-desc: Ipv4 адрес первого DNS сервера
        en-desc: Ipv4 address as first dns
        value: 8.8.8.8
      - name: DNSSRV2
        ru-desc: Ipv4 адрес второго DNS сервера
        en-desc: Ipv4 address as second dns
        value: 8.8.4.4

    - name: NOASK # auto generated params
      noask: true
      generic:
        src-group: IPS
        iterate:
        - replace: IP4 NET4
          noask: true
          value: $GENERIC-MEMBER$value|get_zero_addr
        - replace: IP6 NET6
          noask: true
          value: $GENERIC-MEMBER$value|get_zero_addr


  tasklist:
  - index: 1.2
    add:
      markers: [TUN-IF]
      files:
      - etc/NetworkManager/system-connections/TUN-IF.nmconnection
      - etc/strongswan
      - etc/frr
  - index: 1.6
    add:
      files:
      - root/etc_bckp.sh
      - etc/systemd/system/etc_bckp.service
      - etc/systemd/system/etc_bckp.timer
      - etc/systemd/system/timers.target.wants/etc_bckp.timer
  - index: 1.7
    redefine:
      files:
      - etc/nftables/nftables.nft etc/nftables/nftables-pf.nft
