filemap:
  markers:
    groups:
    - name: IFS # interfaces
      ru-desc: Настройка имен интерфейсов
      en-desc: Interfaces names setup
      members:
      - name: HQ-R-IF
        ru-desc: Интерфейс для соединения с HQ
        en-desc: Interface for HQ connection
        value: enp0s3

    - name: IPS # addresses and masks
      ru-desc: Настройка адресов интерфейсов
      en-desc: Interfaces addresses setup
      generic:
        src-group: IFS
        exclude: [~NAT-IF]
        iterate:
        - append: -IP4
          ru-desc: Ipv4 адрес для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv4 address for $GENERIC-MEMBER$value interface
          values: [192.168.1.2]
        - append: -MASK4
          ru-desc: Ipv4 маска для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv4 mask for $GENERIC-MEMBER$value interface
          values: [24]
        - append: -IP6
          ru-desc: Ipv6 адрес для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv6 address for $GENERIC-MEMBER$value interface
          values: [2000:1::1:2]
        - append: -MASK6
          ru-desc: Ipv6 маска для интерфейса $GENERIC-MEMBER$value
          en-desc: Ipv6 mask for $GENERIC-MEMBER$value interface
          values: [112]

    - name: RTR # router
      ru-desc: Адреса роутера
      en-desc: Router addresses
      members:
      - name: HQ-R-IP4
        ru-desc: Ipv4 адрес HQ-R
        en-desc: Ipv4 address of HQ-R
        value: $HQ-R-IF-IP4$value|get_first_addr
      - name: HQ-R-IP6
        ru-desc: Ipv6 адрес HQ-R
        en-desc: Ipv6 address of HQ-R
        value: $HQ-R-IF-IP6$value|get_first_addr

    - name: DNS # dns
      ru-desc: Настройка серверов DNS
      en-desc: DNS servers setup
      members:
      - name: DNSSRV1
        ru-desc: Ipv4 адрес первого DNS сервера
        en-desc: Ipv4 address as first dns
        value: 8.8.8.8
      - name: DNSSRV2
        ru-desc: Ipv4 адрес второго DNS сервера
        en-desc: Ipv4 address as second dns
        value: 8.8.4.4

  tasklist:
  - index: 1.3
    remove:
      groups: [IPS]
    redefine:
      files:
      - etc/NetworkManager/system-connections/HQ-SRV-IF.nmconnection etc/NetworkManager/system-connections/HQ-SRV-IF-dhcp.nmconnection
