deploy: # VirtualBox vms and network topology
  map:
    ISP: [CLI, HQ-R, BR-R, ~NAT]
    CLI: [ISP]
    HQ-R: [ISP, HQ-SRV]
    BR-R: [ISP, BR-SRV]
    HQ-SRV: [HQ-R]
    BR-SRV: [BR-R]

  packages:
  - name: net-tools
    hosts: ALL
    task: 0
  - name: bind-utils
    hosts: ALL
    task: 0
  - name: nano
    hosts: ALL
    task: 0
  - name: nftables
    hosts: ALL
    task: 0
    units: [nftables.service]
  - name: openssh-server
    hosts: ALL
    task: 0
    units: [sshd.service]
  - name: NetworkManager
    hosts: All
    task: 1.3
    units: [NetworkManager.service]
  - name: NetworkManager-tui
    hosts: All
    task: 1.3
  - name: frr
    hosts: [HQ-R, BR-R]
    task: 1.2
    units: [frr.service]
  - name: strongswan
    hosts: [HQ-R, BR-R]
    task: 1.2
    units: [ipsec.service]
  - name: dhcp-server
    hosts: [HQ-R]
    task: 1.3
    units: [dhcpd.service, dhcpd6.service]
  - name: radvd
    hosts: [HQ-R]
    task: 1.3
    units: [radvd.service]
  - name: iperf3
    hosts: [HQ-R, ISP]
    task: 1.5
  - name: etc-bckp
    hosts: [HQ-R, BR-R]
    task: 1.6
    install: None
    units: [etc_bckp.timer]

  users:
  - name: admin
    password: P@ssw0rd
    hosts: [CLI, HQ-SRV, HQ-R]
    task: 1.4
  - name: branch-admin
    password: P@ssw0rd
    hosts: [BR-SRV, BR-R]
    task: 1.4
  - name: network-admin
    password: P@ssw0rd
    hosts: [HQ-R, BR-SRV, BR-R]
    task: 1.4
